{{- range $name, $sa := .Values.serviceaccounts }}
---
{{- $sa := ternary (lookup "v1" "ServiceAccount" $.Release.Namespace (include "helpers.app.fullname" (dict "name" $name "context" $))) (dict) (not (empty $.Values.version)) -}}
{{- if not $sa }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helpers.app.fullname" (dict "name" $name "context" $) }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
{{- end }}
{{- end }}